version: "3.7"
services:
  mariadb:
    image: mariadb:10.7
    container_name: algalog_db
    restart: always
    networks:
      - algalog-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: algalog

networks:
  algalog-network:
    driver: bridge