server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-type: PKCS12
    key-store-password: changeit

spring:
  datasource:
    password: ${MARIADB_PASS:root}
    url: jdbc:mariadb://algalog_db/algalog?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MARIADB_USER:root}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
